[project]
name = "fastnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.5",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "httpie>=3.2.4",
    "httpx>=0.28.1",
    "requests>=2.32.5",
]
